### ISSUE TITLE
A few questions to better understand the snapshot

### ISSUE THREAD

**Issue by dln949** [scubamuc/scubamuc.github.io#1]
1. Do I understand the snapshot correctly, it DOES include copying the data on my Nextcloud server, such as family photos, family movies, other files we've saved, etc.?
2. I'm not clear on the distinction between export and snapshot. When should I use which one?
3. In the snapshot script, what time of day does the script start?
4. Which day will be the first day this script runs?
5. Once the snapshot script starts, I assume Nextcloud is unavailable until Nextcloud snap starts again - correct?
6. Currently with all the large family movies and photos I've loaded into Nextcloud, the computer Nextcloud is on is about 70% full. That won't present a problem for creating (or restoring) the snapshot? It will place the snapshot on the external media I have mounted in fstab?
7. My Nextcloud is currently about 700GB. How large will the snapshot file be?
8. How can I estimate how long it will take the snapshot script to run (and keep Nextcloud temporarily unavailable)?

Thanks much!

**Comment by scubamuc** [comment]
> 1. Do I understand the snapshot correctly, it DOES include copying the data on my Nextcloud server, such as family photos, family movies, other files we've saved, etc.?

yes, Snap snapshot makes a complete backup of the snap container which includes the complete Nextcloud-snap

> 2. I'm not clear on the distinction between export and snapshot. When should I use which one?

Snap snapshot, see above... Nextcloud-snap export exports database, settings, apps, and data, but is configurable see `-- help`

> 3. In the snapshot script, what time of day does the script start?

This is a personal script I've written for myself and others if they can use it. The script is headless and can be started whenever you like or as a cronjob if you prefer. Thus you should understand cronjobs or automation.

> 4. Which day will be the first day this script runs?

See above

> 5. Once the snapshot script starts, I assume Nextcloud is unavailable until Nextcloud snap starts again - correct?

Yes, usually a couple of seconds. I would set a cronjob for midnight.

> 6. Currently with all the large family movies and photos I've loaded into Nextcloud, the computer Nextcloud is on is about 70% full. That won't present a problem for creating (or restoring) the snapshot? It will place the snapshot on the external media I have mounted in fstab?

That shouldn't be a problem. But I personally keep very few files in the Snap itself. All my data is external and remains on my NAS and not in the Snap. Please consider, the more data you keep in the Snap, the larger the snapshot is and the longer your backup takes.

> 7. My Nextcloud is currently about 700GB. How large will the snapshot file be?

Well 700 GB is a big chunk. Your snapshot will be zipped, so it could be smaller. But I wouldn't trust one single machine with all that data. 

I'd suggest keeping your data on your NAS. My Nextcloud-snap only has 1.5GB of Data, but I access my NAS through Nextcloud-snap. All my data is redundant and remains on the NAS and thus backed up and archived in my home network. My Nextcloud-snap is sort of like a gateway which allows me to access my files on the NAS from anywhere. 

> 8. How can I estimate how long it will take the snapshot script to run (and keep Nextcloud temporarily unavailable)?

Your best bet would be to try it out :-) there is really no way of telling. it depends on your resources ssd, cpu, memory etc. I don't use my own script anymore... I know it works though, I've moved my Nextcloud-snap into an LXD container which allows better management of the Nextcloud-snap machine and enables LXC snapshots with zero downtime.

I'm glad to help you privately, but these are things you'll not get support from the Nextcloud-snap folks. I think most of the Nextcloud folks would ignore your requests too. You should definitely get to know Linux and scripting as well as automation with crontab. I can't help you with that. Make sure to read, read, read the docs.

If you check out my GitHub, you'll see some tips, but you'll have to get into the nitty gritty on your own.

**Comment by scubamuc** [comment]
@dln949 , oh by the way, 

Hi and welcome on my GitHub. 
Yours is the first issue on my GitHub :-) So I hope this issue will be solved.
This is a private GitHub, so nothing official or anything. But its public, so anyone can read/write.

**Comment by dln949** [comment]
Thanks much for the information, much appreciated.
